ALTER TABLE `team_applicant`
  CHANGE COLUMN `time` `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CHANGE COLUMN `status` `status` VARCHAR(25) NULL DEFAULT NULL ;

ALTER TABLE `project_applicant`
  CHANGE COLUMN `time` `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CHANGE COLUMN `status` `status` VARCHAR(25) NULL DEFAULT NULL ;

ALTER TABLE `organization_applicant`
  CHANGE COLUMN `time` `time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  CHANGE COLUMN `status` `status` VARCHAR(25) NULL DEFAULT NULL ;
