CREATE DATABASE IF NOT EXISTS project_fuse;

CREATE TABLE IF NOT EXISTS user (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name TEXT,
  encoded_password TEXT,
  email VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS organization (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name TEXT
);

CREATE TABLE IF NOT EXISTS project (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name TEXT
);

CREATE TABLE IF NOT EXISTS team (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name TEXT
);

CREATE TABLE IF NOT EXISTS session (
  session_id varchar(200) PRIMARY KEY,
  created TIMESTAMP,
  email VARCHAR(500)
);

